import { sql, type Kysely } from 'kysely';

export async function up(db: Kysely<unknown>): Promise<void> {
  await sql`create extension if not exists pgcrypto`.execute(db);
  await sql`
create domain sha256_digest as text check (value ~ '^[a-f0-9]{64}$');
create domain lifecycle_status as text check (value in ('declared','starting','ready','running','completing','completed','blocked','suspended','cancelling','cancelled','failed'));
create domain delivery_status as text check (value in ('ready','leased','completed','failed','dead_lettered','cancelled'));
create domain execution_status as text check (value in ('pending','running','completed','failed','cancelled'));
create domain attempt_status as text check (value in ('pending','leased','running','completed','failed','cancelled','abandoned'));
create domain artifact_state as text check (value in ('staged','committed','tombstoned'));
create table artifact_schemas (id uuid primary key default gen_random_uuid(), name text not null, version text not null, content_digest sha256_digest not null, schema jsonb not null, retired_at timestamptz, created_at timestamptz not null default now(), unique(name, version), unique(name, content_digest));
create table component_definitions (id uuid primary key default gen_random_uuid(), name text not null, version text not null, content_digest sha256_digest not null, definition jsonb not null, retired_at timestamptz, created_at timestamptz not null default now(), unique(name, version), unique(name, content_digest));
create table port_definitions (id uuid primary key default gen_random_uuid(), component_definition_id uuid not null references component_definitions(id), name text not null, direction text not null check(direction in ('input','output','state')), schema_id uuid not null references artifact_schemas(id), required boolean not null default true, created_at timestamptz not null default now(), unique(component_definition_id, name, direction));
create table templates (id uuid primary key default gen_random_uuid(), name text not null, version text not null, content_digest sha256_digest not null, template jsonb not null, retired_at timestamptz, created_at timestamptz not null default now(), unique(name, version), unique(name, content_digest));
create table policies (id uuid primary key default gen_random_uuid(), name text not null, version text not null, content_digest sha256_digest not null, policy jsonb not null, retired_at timestamptz, created_at timestamptz not null default now(), unique(name, version), unique(name, content_digest));
create table regions (id uuid primary key default gen_random_uuid(), parent_region_id uuid references regions(id), name text not null, lifecycle_status lifecycle_status not null default 'declared', lifecycle_epoch integer not null default 0 check(lifecycle_epoch >= 0), active_topology_revision_id uuid, created_at timestamptz not null default now(), unique(parent_region_id, name));
create table topology_revisions (id uuid primary key default gen_random_uuid(), region_id uuid not null references regions(id), revision_number integer not null check(revision_number > 0), content_digest sha256_digest not null, topology jsonb not null, activated_at timestamptz, created_at timestamptz not null default now(), unique(region_id, revision_number), unique(region_id, content_digest));
alter table regions add constraint regions_active_topology_revision_fk foreign key(active_topology_revision_id) references topology_revisions(id);
create table component_instances (id uuid primary key default gen_random_uuid(), region_id uuid not null references regions(id), topology_revision_id uuid not null references topology_revisions(id), component_definition_id uuid not null references component_definitions(id), name text not null, configuration jsonb not null default '{}', lifecycle_status lifecycle_status not null default 'declared', created_at timestamptz not null default now(), unique(topology_revision_id, name));
create table connections (id uuid primary key default gen_random_uuid(), topology_revision_id uuid not null references topology_revisions(id), source_component_instance_id uuid not null references component_instances(id), source_port_name text not null, target_component_instance_id uuid not null references component_instances(id), target_port_name text not null, created_at timestamptz not null default now(), unique(topology_revision_id, source_component_instance_id, source_port_name, target_component_instance_id, target_port_name));
create table commands (id uuid primary key default gen_random_uuid(), region_id uuid not null references regions(id), command_type text not null, payload jsonb not null, status text not null check(status in ('accepted','rejected','completed','cancelled','expired')) default 'accepted', correlation_id text, idempotency_key text, expires_at timestamptz, created_at timestamptz not null default now(), unique(region_id, idempotency_key));
create table events (id uuid primary key default gen_random_uuid(), region_id uuid not null references regions(id), event_type text not null, payload jsonb not null, stream_key text not null, sequence_number bigint not null, command_id uuid references commands(id), execution_id uuid, created_at timestamptz not null default now(), unique(stream_key, sequence_number));
create table deliveries (id uuid primary key default gen_random_uuid(), region_id uuid not null references regions(id), topology_revision_id uuid not null references topology_revisions(id), target_component_instance_id uuid not null references component_instances(id), target_port_name text not null, source_command_id uuid references commands(id), source_event_id uuid references events(id), status delivery_status not null default 'ready', available_at timestamptz not null default now(), lease_owner text, lease_token text, lease_expires_at timestamptz, attempts_count integer not null default 0 check(attempts_count >= 0), created_at timestamptz not null default now(), check ((source_command_id is null) <> (source_event_id is null)));
create index deliveries_ready_idx on deliveries(available_at, created_at) where status = 'ready';
create index deliveries_lease_expiry_idx on deliveries(lease_expires_at) where status = 'leased';
create table executions (id uuid primary key default gen_random_uuid(), delivery_id uuid not null unique references deliveries(id), region_id uuid not null references regions(id), component_instance_id uuid not null references component_instances(id), topology_revision_id uuid not null references topology_revisions(id), lifecycle_epoch integer not null check(lifecycle_epoch >= 0), status execution_status not null default 'pending', completed_at timestamptz, created_at timestamptz not null default now());
alter table events add constraint events_execution_fk foreign key(execution_id) references executions(id);
create table execution_attempts (id uuid primary key default gen_random_uuid(), execution_id uuid not null references executions(id), attempt_number integer not null check(attempt_number > 0), status attempt_status not null default 'pending', lease_owner text, lease_token text, lease_expires_at timestamptz, started_at timestamptz, completed_at timestamptz, failure jsonb, created_at timestamptz not null default now(), unique(execution_id, attempt_number));
create index execution_attempts_lease_expiry_idx on execution_attempts(lease_expires_at) where status in ('leased','running');
create table artifacts (id uuid primary key default gen_random_uuid(), digest_algorithm text not null default 'sha256' check(digest_algorithm = 'sha256'), digest sha256_digest not null, size_bytes bigint not null check(size_bytes >= 0), schema_id uuid not null references artifact_schemas(id), state artifact_state not null, media_type text not null, committed_locator text, provenance jsonb not null, tombstoned_at timestamptz, created_at timestamptz not null default now(), unique(digest_algorithm, digest, size_bytes, schema_id), check((state = 'committed') = (committed_locator is not null)), check((state = 'tombstoned') = (tombstoned_at is not null)));
create table execution_inputs (id uuid primary key default gen_random_uuid(), execution_id uuid not null references executions(id), port_name text not null, artifact_id uuid references artifacts(id), delivery_id uuid not null references deliveries(id), payload jsonb, created_at timestamptz not null default now(), unique(execution_id, port_name, delivery_id));
create table execution_outputs (id uuid primary key default gen_random_uuid(), execution_id uuid not null references executions(id), attempt_id uuid not null references execution_attempts(id), port_name text not null, artifact_id uuid not null references artifacts(id), published_event_id uuid references events(id), created_at timestamptz not null default now(), unique(execution_id, port_name, artifact_id));
create table artifact_derivations (id uuid primary key default gen_random_uuid(), artifact_id uuid not null references artifacts(id), source_artifact_id uuid references artifacts(id), execution_id uuid references executions(id), attempt_id uuid references execution_attempts(id), derivation_type text not null, created_at timestamptz not null default now());
create table artifact_staging (id uuid primary key default gen_random_uuid(), attempt_id uuid not null references execution_attempts(id), staged_ref text not null, digest_algorithm text not null default 'sha256' check(digest_algorithm = 'sha256'), digest sha256_digest not null, size_bytes bigint not null check(size_bytes >= 0), schema_id uuid not null references artifact_schemas(id), media_type text not null, locator text not null, status text not null check(status in ('staged','promoted','abandoned')) default 'staged', metadata jsonb not null default '{}', created_at timestamptz not null default now(), unique(attempt_id, staged_ref), unique(digest_algorithm, digest, size_bytes, schema_id));
create table capabilities (id uuid primary key default gen_random_uuid(), name text not null, version text not null, capability_type text not null, content_digest sha256_digest not null, configuration jsonb not null, retired_at timestamptz, created_at timestamptz not null default now(), unique(name, version), unique(name, content_digest));
create table capability_grants (id uuid primary key default gen_random_uuid(), capability_id uuid not null references capabilities(id), grantee_component_definition_id uuid not null references component_definitions(id), status text not null check(status in ('active','revoked')) default 'active', granted_at timestamptz not null default now(), revoked_at timestamptz, created_at timestamptz not null default now(), unique(capability_id, grantee_component_definition_id));
create table policy_decisions (id uuid primary key default gen_random_uuid(), policy_id uuid references policies(id), subject_kind text not null, subject_id uuid not null, decision text not null check(decision in ('allow','deny','needs_approval')), reason text, context jsonb not null default '{}', created_at timestamptz not null default now());
create table approvals (id uuid primary key default gen_random_uuid(), policy_decision_id uuid not null references policy_decisions(id), status text not null check(status in ('requested','approved','denied','cancelled')) default 'requested', requested_at timestamptz not null default now(), decided_at timestamptz, decided_by text, created_at timestamptz not null default now());
create table external_actions (id uuid primary key default gen_random_uuid(), execution_id uuid not null references executions(id), attempt_id uuid not null references execution_attempts(id), capability_id uuid references capabilities(id), action_type text not null, payload jsonb not null, status text not null check(status in ('proposed','approved','dispatched','completed','failed','cancelled')) default 'proposed', idempotency_key text not null, created_at timestamptz not null default now(), unique(capability_id, idempotency_key));
create table external_action_attempts (id uuid primary key default gen_random_uuid(), external_action_id uuid not null references external_actions(id), attempt_number integer not null check(attempt_number > 0), status text not null check(status in ('pending','dispatched','completed','failed')) default 'pending', requested_at timestamptz not null default now(), completed_at timestamptz, response jsonb, created_at timestamptz not null default now(), unique(external_action_id, attempt_number));
create table resource_ledger (id uuid primary key default gen_random_uuid(), execution_id uuid references executions(id), attempt_id uuid references execution_attempts(id), external_action_id uuid references external_actions(id), resource_type text not null, quantity numeric not null check(quantity >= 0), unit text not null, attributes jsonb not null default '{}', created_at timestamptz not null default now());
create table projection_checkpoints (id uuid primary key default gen_random_uuid(), projection_name text not null, stream_key text not null, last_event_id uuid references events(id), last_sequence_number bigint not null default 0 check(last_sequence_number >= 0), updated_at timestamptz not null default now(), created_at timestamptz not null default now(), unique(projection_name, stream_key));
`.execute(db);
}

export async function down(db: Kysely<unknown>): Promise<void> {
  await sql`
drop table if exists projection_checkpoints, resource_ledger, external_action_attempts, external_actions, approvals, policy_decisions, capability_grants, capabilities, artifact_staging, artifact_derivations, execution_outputs, execution_inputs, artifacts, execution_attempts, executions, deliveries, events, commands, connections, component_instances, topology_revisions, regions, policies, templates, port_definitions, component_definitions, artifact_schemas cascade;
drop domain if exists artifact_state, attempt_status, execution_status, delivery_status, lifecycle_status, sha256_digest cascade;
`.execute(db);
}
