import { sql, type Kysely } from 'kysely';

export async function up(db: Kysely<unknown>): Promise<void> {
  await sql`
create domain uuidv7 as uuid check (substring(value::text from 15 for 1) = '7');
create domain sha256_digest as text check (value ~ '^[a-f0-9]{64}$');
create domain lifecycle_status as text check (value in ('declared','starting','ready','running','completing','completed','blocked','suspended','cancelling','cancelled','failed'));
create domain delivery_status as text check (value in ('ready','leased','completed','failed','dead_lettered','cancelled'));
create domain execution_status as text check (value in ('pending','running','completed','failed','cancelled'));
create domain attempt_status as text check (value in ('pending','leased','running','completed','failed','cancelled','abandoned'));
create domain artifact_state as text check (value in ('staged','committed','tombstoned'));
create domain policy_outcome as text check (value in ('deny','require_approval','modify','allow'));
create domain external_action_status as text check (value in ('proposed','policy_checked','awaiting_approval','authorized','dispatching','acknowledged','reconciled','denied','failed','cancelled','indeterminate'));

create table artifact_schemas (id uuidv7 primary key, name text not null, version text not null, content_digest sha256_digest not null, schema jsonb not null, retired_at timestamptz, created_at timestamptz not null default now(), unique(name, version), unique(name, content_digest));
create table component_definitions (id uuidv7 primary key, name text not null, version text not null, content_digest sha256_digest not null, definition jsonb not null, retired_at timestamptz, created_at timestamptz not null default now(), unique(name, version), unique(name, content_digest));
create table port_definitions (id uuidv7 primary key, component_definition_id uuidv7 not null references component_definitions(id), name text not null, direction text not null check(direction in ('input','output','state')), schema_id uuidv7 not null references artifact_schemas(id), required boolean not null default true, created_at timestamptz not null default now(), unique(component_definition_id, name, direction));
create table templates (id uuidv7 primary key, name text not null, version text not null, content_digest sha256_digest not null, template jsonb not null, retired_at timestamptz, created_at timestamptz not null default now(), unique(name, version), unique(name, content_digest));
create table policies (id uuidv7 primary key, name text not null, version text not null, content_digest sha256_digest not null, policy jsonb not null, retired_at timestamptz, created_at timestamptz not null default now(), unique(name, version), unique(name, content_digest));

create table regions (id uuidv7 primary key, parent_region_id uuidv7 references regions(id), name text not null, lifecycle_status lifecycle_status not null default 'declared', lifecycle_epoch integer not null default 0 check(lifecycle_epoch >= 0), active_topology_revision_id uuidv7, created_at timestamptz not null default now());
create unique index regions_root_name_unique on regions(name) where parent_region_id is null;
create unique index regions_child_name_unique on regions(parent_region_id, name) where parent_region_id is not null;
create table topology_revisions (id uuidv7 primary key, region_id uuidv7 not null references regions(id), revision_number integer not null check(revision_number > 0), content_digest sha256_digest not null, topology jsonb not null, activated_at timestamptz, created_at timestamptz not null default now(), unique(region_id, id), unique(region_id, revision_number), unique(region_id, content_digest));
alter table regions add constraint regions_active_topology_revision_fk foreign key(id, active_topology_revision_id) references topology_revisions(region_id, id) deferrable initially deferred;

create table component_instances (id uuidv7 primary key, region_id uuidv7 not null, topology_revision_id uuidv7 not null, component_definition_id uuidv7 not null references component_definitions(id), name text not null, configuration jsonb not null default '{}', lifecycle_status lifecycle_status not null default 'declared', created_at timestamptz not null default now(), unique(topology_revision_id, id), unique(region_id, topology_revision_id, id), unique(topology_revision_id, name), foreign key(region_id, topology_revision_id) references topology_revisions(region_id, id));
create table connections (id uuidv7 primary key, topology_revision_id uuidv7 not null, source_component_instance_id uuidv7 not null, source_port_name text not null, target_component_instance_id uuidv7 not null, target_port_name text not null, created_at timestamptz not null default now(), unique(topology_revision_id, source_component_instance_id, source_port_name, target_component_instance_id, target_port_name), foreign key(topology_revision_id, source_component_instance_id) references component_instances(topology_revision_id, id), foreign key(topology_revision_id, target_component_instance_id) references component_instances(topology_revision_id, id));

create table commands (id uuidv7 primary key, region_id uuidv7 not null references regions(id), command_type text not null, payload jsonb not null, status text not null check(status in ('accepted','rejected','completed','cancelled','expired')) default 'accepted', correlation_id text, idempotency_key text, expires_at timestamptz, created_at timestamptz not null default now(), unique(region_id, idempotency_key));
create table events (id uuidv7 primary key, region_id uuidv7 not null references regions(id), event_type text not null, payload jsonb not null, stream_key text not null, sequence_number bigint not null, source_kind text not null check(source_kind in ('command','event','execution','attempt','component','system','external_action')), source_command_id uuidv7 references commands(id), source_event_id uuidv7 references events(id), source_execution_id uuidv7, source_attempt_id uuidv7, source_component_instance_id uuidv7, created_at timestamptz not null default now(), unique(stream_key, sequence_number), check(num_nonnulls(source_command_id, source_event_id, source_execution_id, source_attempt_id, source_component_instance_id) >= 1 or source_kind = 'system'));
create table deliveries (id uuidv7 primary key, region_id uuidv7 not null, topology_revision_id uuidv7 not null, target_component_instance_id uuidv7 not null, target_port_name text not null, source_command_id uuidv7 references commands(id), source_event_id uuidv7 references events(id), status delivery_status not null default 'ready', available_at timestamptz not null default now(), lease_owner text, lease_token text, lease_expires_at timestamptz, attempts_count integer not null default 0 check(attempts_count >= 0), completed_at timestamptz, failed_at timestamptz, failure jsonb, created_at timestamptz not null default now(), check ((source_command_id is null) <> (source_event_id is null)), check ((status = 'leased') = (lease_owner is not null and lease_token is not null and lease_expires_at is not null)), check (status = 'leased' or (lease_owner is null and lease_token is null and lease_expires_at is null)), check ((status = 'completed') = (completed_at is not null)), check ((status = 'failed') = (failed_at is not null and failure is not null)), foreign key(region_id, topology_revision_id) references topology_revisions(region_id, id), foreign key(region_id, topology_revision_id, target_component_instance_id) references component_instances(region_id, topology_revision_id, id));
create index deliveries_ready_idx on deliveries(available_at, created_at) where status = 'ready';
create index deliveries_lease_expiry_idx on deliveries(lease_expires_at) where status = 'leased';

create table executions (id uuidv7 primary key, delivery_id uuidv7 not null unique references deliveries(id), region_id uuidv7 not null, component_instance_id uuidv7 not null, topology_revision_id uuidv7 not null, lifecycle_epoch integer not null check(lifecycle_epoch >= 0), status execution_status not null default 'pending', completed_at timestamptz, failed_at timestamptz, failure jsonb, created_at timestamptz not null default now(), unique(id, region_id), unique(id, component_instance_id), check ((status = 'completed') = (completed_at is not null)), check ((status = 'failed') = (failed_at is not null and failure is not null)), foreign key(region_id, topology_revision_id, component_instance_id) references component_instances(region_id, topology_revision_id, id));
create table execution_attempts (id uuidv7 primary key, execution_id uuidv7 not null references executions(id), attempt_number integer not null check(attempt_number > 0), status attempt_status not null default 'pending', lease_owner text, lease_token text, lease_expires_at timestamptz, started_at timestamptz, completed_at timestamptz, failure jsonb, created_at timestamptz not null default now(), unique(execution_id, id), unique(execution_id, attempt_number), check ((status in ('leased','running')) = (lease_owner is not null and lease_token is not null and lease_expires_at is not null)), check (status in ('leased','running') or (lease_owner is null and lease_token is null and lease_expires_at is null)), check ((status = 'completed') = (completed_at is not null)), check ((status = 'failed') = (completed_at is not null and failure is not null)));
alter table events add constraint events_source_execution_fk foreign key(source_execution_id) references executions(id);
alter table events add constraint events_source_attempt_fk foreign key(source_execution_id, source_attempt_id) references execution_attempts(execution_id, id);
alter table events add constraint events_source_component_fk foreign key(source_component_instance_id) references component_instances(id);
create index execution_attempts_lease_expiry_idx on execution_attempts(lease_expires_at) where status in ('leased','running');

create table artifacts (id uuidv7 primary key, digest_algorithm text not null default 'sha256' check(digest_algorithm = 'sha256'), digest sha256_digest not null, size_bytes bigint not null check(size_bytes >= 0), schema_id uuidv7 not null references artifact_schemas(id), state artifact_state not null, media_type text not null, committed_locator text, provenance jsonb not null, tombstoned_at timestamptz, created_at timestamptz not null default now(), unique(digest_algorithm, digest), unique(digest_algorithm, digest, size_bytes, schema_id), check((state = 'committed') = (committed_locator is not null)), check((state = 'tombstoned') = (tombstoned_at is not null)));
create table execution_inputs (id uuidv7 primary key, execution_id uuidv7 not null references executions(id), port_name text not null, artifact_id uuidv7 references artifacts(id), delivery_id uuidv7 not null references deliveries(id), payload jsonb, created_at timestamptz not null default now(), unique(execution_id, port_name, delivery_id));
create table execution_outputs (id uuidv7 primary key, execution_id uuidv7 not null, attempt_id uuidv7 not null, port_name text not null, artifact_id uuidv7 not null references artifacts(id), published_event_id uuidv7 references events(id), created_at timestamptz not null default now(), unique(execution_id, port_name, artifact_id), foreign key(execution_id, attempt_id) references execution_attempts(execution_id, id));
create table artifact_derivations (id uuidv7 primary key, artifact_id uuidv7 not null references artifacts(id), source_artifact_id uuidv7 references artifacts(id), execution_id uuidv7, attempt_id uuidv7, derivation_type text not null, created_at timestamptz not null default now(), foreign key(execution_id, attempt_id) references execution_attempts(execution_id, id));
create table artifact_staging (id uuidv7 primary key, attempt_id uuidv7 not null references execution_attempts(id), staged_ref text not null, digest_algorithm text not null default 'sha256' check(digest_algorithm = 'sha256'), digest sha256_digest not null, size_bytes bigint not null check(size_bytes >= 0), schema_id uuidv7 not null references artifact_schemas(id), media_type text not null, locator text not null, status text not null check(status in ('staged','promoted','abandoned')) default 'staged', metadata jsonb not null default '{}', created_at timestamptz not null default now(), unique(attempt_id, staged_ref));

create table capabilities (id uuidv7 primary key, name text not null, version text not null, capability_type text not null, content_digest sha256_digest not null, configuration jsonb not null, retired_at timestamptz, created_at timestamptz not null default now(), unique(name, version), unique(name, content_digest));
create table capability_grants (id uuidv7 primary key, capability_id uuidv7 not null references capabilities(id), grantee_component_definition_id uuidv7 not null references component_definitions(id), status text not null check(status in ('active','revoked')) default 'active', granted_at timestamptz not null default now(), revoked_at timestamptz, created_at timestamptz not null default now(), unique(capability_id, grantee_component_definition_id), check ((status = 'revoked') = (revoked_at is not null)));
create table policy_decisions (id uuidv7 primary key, policy_id uuidv7 references policies(id), policy_name text not null, policy_version text not null, evaluator_version text not null, subject_kind text not null, subject_id uuidv7 not null, input_artifact_id uuidv7 references artifacts(id), normalized_inputs jsonb not null, outcome policy_outcome not null, reason text, modifications jsonb not null default '[]', created_at timestamptz not null default now(), check (outcome = 'modify' or modifications = '[]'::jsonb));
create table approvals (id uuidv7 primary key, policy_decision_id uuidv7 not null references policy_decisions(id), status text not null check(status in ('requested','approved','denied','cancelled')) default 'requested', requested_at timestamptz not null default now(), decided_at timestamptz, decided_by text, created_at timestamptz not null default now(), check ((status in ('approved','denied','cancelled')) = (decided_at is not null)), check ((status in ('approved','denied')) = (decided_by is not null)));
create table external_actions (id uuidv7 primary key, execution_id uuidv7 not null, attempt_id uuidv7 not null, capability_grant_id uuidv7 not null references capability_grants(id), outbound_request_artifact_id uuidv7 not null references artifacts(id), policy_decision_id uuidv7 references policy_decisions(id), approval_id uuidv7 references approvals(id), action_type text not null, status external_action_status not null default 'proposed', idempotency_key text not null, created_at timestamptz not null default now(), unique(capability_grant_id, action_type, idempotency_key), foreign key(execution_id, attempt_id) references execution_attempts(execution_id, id), check ((status in ('awaiting_approval','authorized','dispatching','acknowledged','reconciled')) = (policy_decision_id is not null) or status in ('proposed','denied','failed','cancelled','indeterminate')));
create table external_action_attempts (id uuidv7 primary key, external_action_id uuidv7 not null references external_actions(id), attempt_number integer not null check(attempt_number > 0), status text not null check(status in ('pending','dispatching','acknowledged','failed','indeterminate')) default 'pending', requested_at timestamptz not null default now(), completed_at timestamptz, response jsonb, created_at timestamptz not null default now(), unique(external_action_id, attempt_number), check ((status in ('acknowledged','failed','indeterminate')) = (completed_at is not null)));
create table resource_ledger (id uuidv7 primary key, region_id uuidv7 not null references regions(id), execution_id uuidv7, attempt_id uuidv7, external_action_id uuidv7 references external_actions(id), resource_type text not null, quantity numeric(38, 12) not null check(quantity >= 0), unit text not null, attributes jsonb not null default '{}', created_at timestamptz not null default now(), check (execution_id is not null or external_action_id is not null), foreign key(execution_id, attempt_id) references execution_attempts(execution_id, id));
create table projection_checkpoints (id uuidv7 primary key, projection_name text not null, stream_key text not null, last_event_id uuidv7 references events(id), last_sequence_number bigint not null default 0 check(last_sequence_number >= 0), updated_at timestamptz not null default now(), created_at timestamptz not null default now(), unique(projection_name, stream_key));
`.execute(db);
}

export async function down(db: Kysely<unknown>): Promise<void> {
  await sql`
drop table if exists projection_checkpoints, resource_ledger, external_action_attempts, external_actions, approvals, policy_decisions, capability_grants, capabilities, artifact_staging, artifact_derivations, execution_outputs, execution_inputs, artifacts, execution_attempts, executions, deliveries, events, commands, connections, component_instances, topology_revisions, regions, policies, templates, port_definitions, component_definitions, artifact_schemas cascade;
drop domain if exists external_action_status, policy_outcome, artifact_state, attempt_status, execution_status, delivery_status, lifecycle_status, sha256_digest, uuidv7 cascade;
`.execute(db);
}
