# generated by datamodel-codegen:
#   filename:  admin/artifact-schema-registration.schema.json

from __future__ import annotations

from typing import Any, Literal

from pydantic import BaseModel, ConfigDict, constr


class Metadata(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    name: constr(min_length=1)
    version: constr(min_length=1)


class Model(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    apiVersion: Literal['factory-floor.dev/v1alpha1']
    kind: Literal['ArtifactSchema']
    metadata: Metadata
    spec: dict[str, Any]
