# generated by datamodel-codegen:
#   filename:  _internal

from __future__ import annotations

from typing import Literal
from uuid import UUID

from pydantic import BaseModel, ConfigDict, Field, RootModel, conint, constr


class Sha256Digest(RootModel[constr(pattern=r'^[a-f0-9]{64}$')]):
    root: constr(pattern=r'^[a-f0-9]{64}$')


class ArtifactDescriptor(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    artifactId: UUID
    digest: Sha256Digest
    sizeBytes: conint(ge=0)
    mediaType: constr(min_length=1)
    schemaId: constr(min_length=1)
    schemaDigest: Sha256Digest
    uri: constr(min_length=1)
    provenance: SourceIdentity


class SourceIdentity1(BaseModel):
    """
    Identity of the runtime object or actor that caused an invocation, proposal, or artifact.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    kind: Literal['command']
    commandId: UUID
    submittedBy: constr(min_length=1)


class SourceIdentity2(BaseModel):
    """
    Identity of the runtime object or actor that caused an invocation, proposal, or artifact.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    kind: Literal['event']
    eventId: UUID
    producerComponentId: UUID


class SourceIdentity3(BaseModel):
    """
    Identity of the runtime object or actor that caused an invocation, proposal, or artifact.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    kind: Literal['artifact']
    artifactId: UUID
    digest: Sha256Digest


class SourceIdentity(RootModel[SourceIdentity1 | SourceIdentity2 | SourceIdentity3]):
    root: SourceIdentity1 | SourceIdentity2 | SourceIdentity3 = Field(
        ...,
        description='Identity of the runtime object or actor that caused an invocation, proposal, or artifact.',
        title='SourceIdentity',
    )
