# generated by datamodel-codegen:
#   filename:  external-action-proposal.schema.json

from __future__ import annotations

from enum import Enum
from uuid import UUID

from pydantic import BaseModel, ConfigDict, constr

from . import staged_artifact_schema


class Risk(Enum):
    low = 'low'
    medium = 'medium'
    high = 'high'
    irreversible = 'irreversible'


class ExternalActionProposal(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    proposalId: UUID
    actionType: constr(min_length=1)
    idempotencyKey: constr(min_length=1)
    capabilityHandle: constr(min_length=1)
    requestArtifact: staged_artifact_schema.StagedArtifact
    risk: Risk
