# generated by datamodel-codegen:
#   filename:  failure-descriptor.schema.json

from __future__ import annotations

from enum import Enum
from typing import Any

from pydantic import BaseModel, ConfigDict, constr


class Category(Enum):
    invalid_input = 'invalid_input'
    schema_mismatch = 'schema_mismatch'
    capability_denied = 'capability_denied'
    policy_denied = 'policy_denied'
    timeout = 'timeout'
    dependency = 'dependency'
    model = 'model'
    cancelled = 'cancelled'
    unknown = 'unknown'


class FailureDescriptor(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    code: constr(min_length=1)
    message: constr(min_length=1)
    category: Category
    retryable: bool
    details: dict[str, Any] | None = None
