# generated by datamodel-codegen:
#   filename:  invocation-envelope.schema.json

from __future__ import annotations

from typing import Any, Literal
from uuid import UUID

from pydantic import AnyUrl, AwareDatetime, BaseModel, ConfigDict, conint, constr

from ._internal import ArtifactDescriptor, SourceIdentity


class Component(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    componentId: UUID
    definitionId: constr(min_length=1)
    configuration: Any


class InvocationEnvelope(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    protocolVersion: Literal['1.0']
    executionId: UUID
    attemptId: UUID
    leaseToken: constr(min_length=1)
    leaseExpiresAt: AwareDatetime
    lifecycleEpoch: conint(ge=0)
    component: Component
    inputs: list[ArtifactDescriptor]
    state: ArtifactDescriptor | None
    capabilityHandles: list[constr(min_length=1)]
    cancellationUrl: AnyUrl
    heartbeatUrl: AnyUrl
    traceContext: dict[str, str]
    source: SourceIdentity
