# generated by datamodel-codegen:
#   filename:  invocation-envelope.schema.json

from __future__ import annotations

from typing import Any, Literal
from uuid import UUID

from pydantic import AnyUrl, AwareDatetime, BaseModel, ConfigDict, conint, constr

from ._internal import ArtifactDescriptor, SourceIdentity


class Component(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    componentId: UUID
    definitionId: UUID
    definitionName: constr(min_length=1)
    definitionVersion: constr(min_length=1)
    definition: Any
    configuration: Any


class Limits(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    heartbeatIntervalMs: conint(ge=1)
    maxArtifactBytes: conint(ge=1)


class Input(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    portName: str
    deliveryId: UUID
    payload: Any
    artifacts: list[ArtifactDescriptor]
    artifactReadUrls: list[AnyUrl]


class InvocationEnvelope(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    protocolVersion: Literal['1.0']
    executionId: UUID
    attemptId: UUID
    attemptNumber: conint(ge=1)
    leaseToken: constr(min_length=1)
    leaseExpiresAt: AwareDatetime
    lifecycleEpoch: conint(ge=0)
    component: Component
    inputs: list[Input]
    state: ArtifactDescriptor | None
    capabilityHandles: list[constr(min_length=1)]
    cancellationUrl: AnyUrl
    heartbeatUrl: AnyUrl
    resultSubmissionUrl: AnyUrl
    artifactStagingUrl: AnyUrl
    capabilityInvocationUrl: AnyUrl
    traceContext: dict[str, str]
    limits: Limits
    source: SourceIdentity
