# generated by datamodel-codegen:
#   filename:  proposed-event.schema.json

from __future__ import annotations

from typing import Any

from pydantic import AwareDatetime, BaseModel, ConfigDict, constr

from ._internal import Sha256Digest, SourceIdentity


class ProposedEvent(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    eventType: constr(min_length=1)
    subject: constr(min_length=1)
    payload: Any
    schemaId: constr(min_length=1)
    schemaDigest: Sha256Digest
    occurredAt: AwareDatetime
    source: SourceIdentity
