# generated by datamodel-codegen:
#   filename:  repository-task-recipe-invocation.schema.json

from __future__ import annotations

from typing import Any

from pydantic import BaseModel, ConfigDict, constr


class RepositoryTaskRecipeInvocation(BaseModel):
    """
    A versioned deterministic recipe selection and its bounded inputs. Recipe resolution remains repository-owned.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    name: constr(pattern=r'^[a-z][a-z0-9-]{0,63}$')
    version: constr(pattern=r'^[1-9][0-9]*$')
    inputs: dict[str, Any]
