# generated by datamodel-codegen:
#   filename:  repository-task-normalized-plan.schema.json

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, ConfigDict, Field, RootModel, conint, constr

from . import (
    repository_task_declared_output_schema,
    repository_task_recipe_invocation_schema,
)


class AllowedPath(RootModel[constr(min_length=1, max_length=512)]):
    root: constr(min_length=1, max_length=512)


class RequestedCapability(
    RootModel[constr(pattern=r'^[a-z][a-zA-Z0-9]*(\.[a-z][a-zA-Z0-9]*)+$')]
):
    root: constr(pattern=r'^[a-z][a-zA-Z0-9]*(\.[a-z][a-zA-Z0-9]*)+$')


class CompletionCriterion(RootModel[constr(min_length=1, max_length=512)]):
    root: constr(min_length=1, max_length=512)


class Repository(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    owner: constr(min_length=1, max_length=39)
    name: constr(min_length=1, max_length=100)
    baseRevision: constr(pattern=r'^[a-f0-9]{40}$')


class ResourceBounds(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    maxFiles: conint(ge=1, le=100)
    maxPatchBytes: conint(ge=1, le=10485760)
    maxVerificationSeconds: conint(ge=1, le=3600)


class RepositoryTaskNormalizedPlan(BaseModel):
    """
    Canonical replayable state derived from authored repository-task intent. The digest covers this object without planDigest and does not represent a policy grant.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    schemaVersion: Literal[1]
    objective: constr(min_length=1, max_length=1000)
    repository: Repository
    allowedPaths: list[AllowedPath] = Field(..., max_length=100, min_length=1)
    recipe: repository_task_recipe_invocation_schema.RepositoryTaskRecipeInvocation
    outputs: list[
        repository_task_declared_output_schema.RepositoryTaskDeclaredOutput
    ] = Field(..., max_length=100, min_length=1)
    verificationProfile: constr(pattern=r'^[a-z][a-z0-9-]{0,63}$')
    resourceBounds: ResourceBounds
    requestedCapabilities: list[RequestedCapability] = Field(..., max_length=32)
    completionCriteria: list[CompletionCriterion] = Field(
        ..., max_length=32, min_length=1
    )
    planDigest: constr(pattern=r'^[a-f0-9]{64}$')
