# generated by datamodel-codegen:
#   filename:  repository-task-declared-output.schema.json

from __future__ import annotations

from enum import Enum

from pydantic import BaseModel, ConfigDict, constr


class Kind(Enum):
    file = 'file'
    test = 'test'
    export = 'export'
    evidence = 'evidence'


class RepositoryTaskDeclaredOutput(BaseModel):
    """
    One immutable output promised by a normalized repository-task plan. Outputs describe required evidence or proposed repository content; they do not grant write authority.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    name: constr(pattern=r'^[a-z][a-z0-9-]{0,63}$')
    kind: Kind
    path: constr(min_length=1, max_length=512)
    mediaType: constr(
        pattern=r'^[a-z0-9][a-z0-9!#$&^_.+-]*/[a-z0-9][a-z0-9!#$&^_.+-]*$'
    )
    required: bool
