# generated by datamodel-codegen:
#   filename:  repository-task-diagnostic.schema.json

from __future__ import annotations

from enum import Enum

from pydantic import BaseModel, ConfigDict, constr


class Severity(Enum):
    error = 'error'
    warning = 'warning'


class RepositoryTaskDiagnostic(BaseModel):
    """
    A stable machine-readable diagnostic emitted while validating or normalizing repository-task intent.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    code: constr(pattern=r'^[a-z][a-z0-9-]*(\.[a-z][a-z0-9-]*)+$')
    severity: Severity
    path: constr(pattern=r'^(/([^/~]|~0|~1)*)*$')
    message: constr(min_length=1, max_length=512)
