# generated by datamodel-codegen:
#   filename:  repository-task-recipe-invocation.schema.json

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, ConfigDict, constr


class Inputs(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    package: constr(pattern=r'^@[a-z0-9][a-z0-9-]*/[a-z0-9][a-z0-9-]*$')
    moduleName: constr(pattern=r'^[a-z][a-z0-9-]{0,63}$')


class RepositoryTaskRecipeInvocation(BaseModel):
    """
    A versioned deterministic recipe selection and its bounded typed inputs. Recipe resolution remains repository-owned.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    name: Literal['typescript-module']
    version: constr(pattern=r'^[1-9][0-9]*$')
    inputs: Inputs
