# generated by datamodel-codegen:
#   filename:  resource-usage.schema.json

from __future__ import annotations

from pydantic import BaseModel, ConfigDict, conint


class ResourceUsage(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    cpuMilliseconds: conint(ge=0)
    wallMilliseconds: conint(ge=0)
    inputBytes: conint(ge=0)
    outputBytes: conint(ge=0)
    externalCalls: conint(ge=0)
