# generated by datamodel-codegen:
#   filename:  staged-artifact.schema.json

from __future__ import annotations

from uuid import UUID

from pydantic import BaseModel, ConfigDict, conint, constr

from ._internal import Sha256Digest, SourceIdentity


class StagedArtifact(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    stagingId: UUID
    portName: constr(min_length=1)
    digest: Sha256Digest
    sizeBytes: conint(ge=0)
    mediaType: constr(min_length=1)
    schemaId: constr(min_length=1)
    schemaDigest: Sha256Digest
    provenance: SourceIdentity
