# generated by datamodel-codegen:
#   filename:  template-instantiation-error.schema.json

from __future__ import annotations

from enum import Enum
from typing import Literal

from pydantic import BaseModel, ConfigDict, constr


class Code(Enum):
    invalid_declaration = 'invalid_declaration'
    unsupported_declaration_version = 'unsupported_declaration_version'
    duplicate_port_identity = 'duplicate_port_identity'
    duplicate_ingress_target = 'duplicate_ingress_target'
    duplicate_component_instance = 'duplicate_component_instance'
    duplicate_region_identity = 'duplicate_region_identity'
    duplicate_connection = 'duplicate_connection'
    component_definition_not_found = 'component_definition_not_found'
    component_definition_retired = 'component_definition_retired'
    component_not_allowed = 'component_not_allowed'
    template_not_found = 'template_not_found'
    template_retired = 'template_retired'
    invalid_template_parameters = 'invalid_template_parameters'
    invalid_component_configuration = 'invalid_component_configuration'
    artifact_schema_not_found = 'artifact_schema_not_found'
    artifact_schema_retired = 'artifact_schema_retired'
    policy_not_found = 'policy_not_found'
    policy_retired = 'policy_retired'
    capability_not_found = 'capability_not_found'
    capability_retired = 'capability_retired'
    region_not_found = 'region_not_found'
    region_not_eligible = 'region_not_eligible'
    invalid_port_reference = 'invalid_port_reference'
    incompatible_port_schema = 'incompatible_port_schema'
    missing_required_output = 'missing_required_output'
    invalid_fan_in_rule = 'invalid_fan_in_rule'
    template_instantiation_conflict = 'template_instantiation_conflict'
    internal_transient_failure = 'internal_transient_failure'


class TemplateInstantiationError(BaseModel):
    """
    Stable error envelope returned by the authoritative template-instantiation boundary.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    protocolVersion: Literal['1.0']
    code: Code
    message: constr(min_length=1)
    retryable: bool
