# generated by datamodel-codegen:
#   filename:  template-instantiation-request.schema.json

from __future__ import annotations

from typing import Any, Literal
from uuid import UUID

from pydantic import BaseModel, ConfigDict, RootModel, constr


class Sha256Digest(RootModel[constr(pattern=r'^[a-f0-9]{64}$')]):
    root: constr(pattern=r'^[a-f0-9]{64}$')


class NaturalKey(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    name: constr(min_length=1, max_length=128)
    version: constr(min_length=1, max_length=128)
    expectedContentDigest: Sha256Digest | None = None


class SystemSource(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    kind: Literal['system']
    name: constr(min_length=1, max_length=128)
    version: constr(min_length=1, max_length=128)
    contentDigest: Sha256Digest


class RegionRequestSource(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    kind: Literal['regionRequest']
    requestId: UUID
    parentRegionId: UUID
    requesterComponentInstanceId: UUID


class InternalSource(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    kind: Literal['internal']
    operation: constr(min_length=1, max_length=128)


class Source(RootModel[SystemSource | RegionRequestSource | InternalSource]):
    root: SystemSource | RegionRequestSource | InternalSource


class TemplateInstantiationRequest(BaseModel):
    """
    Versioned authoritative request to instantiate one registered template into an eligible target region.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    protocolVersion: Literal['1.0']
    requestId: UUID
    targetRegionId: UUID
    template: NaturalKey
    parameters: dict[str, Any] | None = {}
    componentConfiguration: dict[str, dict[str, Any]] | None = {}
    source: Source
