# generated by datamodel-codegen:
#   filename:  worker/cancellation-response.schema.json

from __future__ import annotations

from enum import Enum
from typing import Literal

from pydantic import BaseModel, ConfigDict


class State(Enum):
    continue_ = 'continue'
    cancellation_requested = 'cancellation_requested'
    lease_no_longer_valid = 'lease_no_longer_valid'
    attempt_terminal = 'attempt_terminal'


class WorkerCancellationResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    protocolVersion: Literal['1.0']
    state: State
