# generated by datamodel-codegen:
#   filename:  worker/capability-response.schema.json

from __future__ import annotations

from typing import Any, Literal

from pydantic import BaseModel, ConfigDict, constr


class WorkerCapabilityResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    protocolVersion: Literal['1.0']
    output: dict[str, Any]
    auditId: constr(min_length=1)
