# generated by datamodel-codegen:
#   filename:  worker/capability-request.schema.json

from __future__ import annotations

from typing import Any, Literal
from uuid import UUID

from pydantic import BaseModel, ConfigDict, conint, constr


class WorkerCapabilityRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    protocolVersion: Literal['1.0']
    executionId: UUID
    attemptId: UUID
    leaseToken: constr(min_length=1)
    lifecycleEpoch: conint(ge=0)
    handle: constr(min_length=1)
    input: dict[str, Any]
