# generated by datamodel-codegen:
#   filename:  worker/claim-request.schema.json

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, ConfigDict, Field, RootModel, constr


class Capability(RootModel[constr(min_length=1, max_length=128)]):
    root: constr(min_length=1, max_length=128)


class WorkerClaimRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    protocolVersion: Literal['1.0']
    workerId: constr(min_length=1, max_length=128)
    capabilities: list[Capability] = Field(..., max_length=64)
