# generated by datamodel-codegen:
#   filename:  worker/claim-response.schema.json

from __future__ import annotations

from typing import Any, Literal

from pydantic import BaseModel, ConfigDict, Field, RootModel, conint


class WorkerClaimResponse1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    protocolVersion: Literal['1.0']
    claimed: Literal[True]
    envelope: Any


class WorkerClaimResponse2(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    protocolVersion: Literal['1.0']
    claimed: Literal[False]
    retryAfterMs: conint(ge=0, le=60000)


class WorkerClaimResponse(RootModel[WorkerClaimResponse1 | WorkerClaimResponse2]):
    root: WorkerClaimResponse1 | WorkerClaimResponse2 = Field(
        ..., title='WorkerClaimResponse'
    )
