# generated by datamodel-codegen:
#   filename:  worker/error.schema.json

from __future__ import annotations

from typing import Any, Literal

from pydantic import BaseModel, ConfigDict, constr


class WorkerError(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    protocolVersion: Literal['1.0']
    code: constr(pattern=r'^[a-z0-9_]+$')
    message: constr(min_length=1, max_length=512)
    retryable: bool
    requestId: constr(min_length=1)
    details: dict[str, Any] | None = None
