# generated by datamodel-codegen:
#   filename:  worker/heartbeat-response.schema.json

from __future__ import annotations

from enum import Enum
from typing import Literal

from pydantic import AwareDatetime, BaseModel, ConfigDict


class Cancellation(Enum):
    continue_ = 'continue'
    cancellation_requested = 'cancellation_requested'


class WorkerHeartbeatResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    protocolVersion: Literal['1.0']
    leaseValid: bool
    leaseExpiresAt: AwareDatetime
    cancellation: Cancellation
