# generated by datamodel-codegen:
#   filename:  worker/stage-response.schema.json

from __future__ import annotations

from typing import Literal

from pydantic import AwareDatetime, BaseModel, ConfigDict, constr


class WorkerStageResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    protocolVersion: Literal['1.0']
    stagedRef: constr(min_length=1)
    uploadUrl: str
    expiresAt: AwareDatetime
