# generated by datamodel-codegen:
#   filename:  worker/stage-request.schema.json

from __future__ import annotations

from typing import Any, Literal
from uuid import UUID

from pydantic import BaseModel, ConfigDict, conint, constr


class WorkerStageRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    protocolVersion: Literal['1.0']
    executionId: UUID
    attemptId: UUID
    leaseToken: constr(min_length=1)
    lifecycleEpoch: conint(ge=0)
    portName: constr(min_length=1, max_length=128)
    mediaType: constr(min_length=1, max_length=255)
    expectedDigest: constr(pattern=r'^[a-f0-9]{64}$')
    expectedSizeBytes: conint(ge=0, le=104857600)
    metadata: dict[str, Any]
