# generated by datamodel-codegen:
#   filename:  worker/upload-response.schema.json

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, ConfigDict, conint, constr


class WorkerUploadResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    protocolVersion: Literal['1.0']
    stagedRef: str
    digest: constr(pattern=r'^[a-f0-9]{64}$')
    sizeBytes: conint(ge=0)
